# Note: additional setup is required, see https://www.jenkins.io/redirect/continuous-delivery-of-plugins

name: cd
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the workflow'
        required: true

permissions:
  checks: read
  contents: write

jobs:
  maven-cd:
    if: ${{ github.event.inputs.environment == 'release' }}
    uses: jenkins-infra/github-reusable-workflows/.github/workflows/maven-cd.yml@v1
    secrets:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}